In [1]:
import numpy as np
import cv2 as cv
import glob
import matplotlib.pyplot as plt

In [2]:
num_of_rows = 8
num_of_cols = 6

# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((num_of_rows*num_of_cols,3), np.float32)
objp[:,:2] = np.mgrid[0:num_of_rows, 0:num_of_cols].T.reshape(-1,2)
objp[:, [0,1]] = objp[:, [1,0]]
# the square length is 30 mm
squareSize = 30
objp = squareSize * objp


In [8]:
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
images = glob.glob('./images1/FD2/*.jpg')
# images = glob.glob('*.jpg')

for fname in images:
    img = cv.imread(fname)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (num_of_rows, num_of_cols), None)
    # If found, add object points, image points (after refining them)
    if ret == True:
        print("Found");
        objpoints.append(objp)
        corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners)
        # Draw and display the corners
        cv.drawChessboardCorners(img, (num_of_rows, num_of_cols), corners2, ret)
        # plt.figure(figsize=(10,10))
        # plt.imshow(img)
        cv.namedWindow("img",0);
        cv.resizeWindow("img", 640, 480);
        cv.imshow('img', img)
        cv.waitKey(5000)
        cv.destroyAllWindows()
    else:
        print("Failed")


Found
Found


In [4]:
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
print("Camera matrix : \n")
print(mtx)
print("\n\ndist : \n")
print(dist)


Camera matrix : 

[[3.40707057e+03 0.00000000e+00 1.57502749e+03]
 [0.00000000e+00 3.40761563e+03 2.02182558e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


dist : 

[[ 3.06816898e-01 -1.22909298e+00  4.28602242e-03  8.69834486e-05
  -7.92360900e-01]]


In [9]:
print("rvecs : \n")
print(rvecs)
print("\n\ntvecs : \n")
print(tvecs)

rvecs : 

(array([[0.0038672 ],
       [3.11409   ],
       [0.18074742]]), array([[0.03515469],
       [2.8448833 ],
       [0.15917019]]))


tvecs : 

(array([[  72.62951434],
       [-102.50730894],
       [ 320.29684412]]), array([[  72.41530298],
       [-103.83732986],
       [ 349.33633403]]))
